export const diseasesData = [
  {
    id: "diabetes",
    name_en: "Diabetes",
    name_hi: "मधुमेह",
    description_en: "A disease that occurs when your blood glucose is too high.",
    description_hi: "एक बीमारी जो तब होती है जब आपके रक्त में शर्करा का स्तर बहुत अधिक हो जाता है।",
    causes_en: "Genetics, obesity, lack of physical activity.",
    causes_hi: "आनुवंशिकी, मोटापा, शारीरिक गतिविधि की कमी।",
    symptoms_en: "Increased thirst, frequent urination, fatigue.",
    symptoms_hi: "प्यास बढ़ना, बार-बार पेशाब आना, थकान।",
    remedies_en: "Fenugreek seeds, Bitter gourd, Cinnamon.",
    remedies_hi: "मेथी के बीज, करेला, दालचीनी।",
    yoga_en: "Dhanurasana, Paschimottanasana, Ardha Matsyendrasana.",
    yoga_hi: "धनुरासन, पश्चिमोत्तानासन, अर्ध मत्स्येन्द्रासन।",
    dos_en: "Eat whole grains, exercise daily, monitor blood sugar.",
    dos_hi: "साबुत अनाज खाएं, रोजाना व्यायाम करें, ब्लड शुगर की निगरानी करें।",
    donts_en: "Avoid sugary drinks, processed foods, and excessive stress.",
    donts_hi: "मीठे पेय, प्रसंस्कृत खाद्य पदार्थ और अत्यधिक तनाव से बचें।",
    consult_doctor_en: "If blood sugar remains consistently high or you feel dizzy.",
    consult_doctor_hi: "यदि ब्लड शुगर लगातार उच्च बना रहे या आपको चक्कर आए।",
  },
  {
    id: "bp",
    name_en: "Blood Pressure (Hypertension)",
    name_hi: "रक्तचाप (हाइपरटेंशन)",
    description_en: "When the force of the blood against the artery walls is too high.",
    description_hi: "जब धमनी की दीवारों के खिलाफ रक्त का बल बहुत अधिक होता है।",
    causes_en: "High salt intake, stress, smoking, sedentary lifestyle.",
    causes_hi: "नमक का अधिक सेवन, तनाव, धूम्रपान, सुस्त जीवनशैली।",
    symptoms_en: "Headaches, shortness of breath, nosebleeds.",
    symptoms_hi: "सिरदर्द, सांस की तकलीफ, नाक से खून आना।",
    remedies_en: "Garlic, Hibiscus tea, Potassium-rich foods.",
    remedies_hi: "लहसुन, गुड़हल की चाय, पोटेशियम युक्त खाद्य पदार्थ।",
    yoga_en: "Shavasana, Bhujangasana, Anulom Vilom.",
    yoga_hi: "शवासन, भुजंगासन, अनुलोम विलोम।",
    dos_en: "Reduce salt, walk 30 mins daily, practice deep breathing.",
    dos_hi: "नमक कम करें, रोजाना 30 मिनट चलें, गहरी सांस लेने का अभ्यास करें।",
    donts_en: "Avoid caffeine, alcohol, and high-fat foods.",
    donts_hi: "कैफीन, शराब और उच्च वसा वाले खाद्य पदार्थों से बचें।",
    consult_doctor_en: "If BP exceeds 140/90 consistently or severe headache occurs.",
    consult_doctor_hi: "यदि बीपी लगातार 140/90 से अधिक हो या गंभीर सिरदर्द हो।",
  },
  {
    id: "thyroid",
    name_en: "Thyroid",
    name_hi: "थायराइड",
    description_en: "Disorders of the thyroid gland, affecting metabolism.",
    description_hi: "थायराइड ग्रंथी के विकार, जो मेटाबॉलिज्म को प्रभावित करते हैं।",
    causes_en: "Iodine deficiency, autoimmune diseases.",
    causes_hi: "आयोडीन की कमी, ऑटोइम्यून बीमारियां।",
    symptoms_en: "Weight change, fatigue, neck swelling.",
    symptoms_hi: "वजन में बदलाव, थकान, गर्दन में सूजन।",
    remedies_en: "Ginger tea, Walnuts, Brazil nuts.",
    remedies_hi: "अदरक की चाय, अखरोट, ब्राजील नट्स।",
    yoga_en: "Sarvangasana, Matsyasana, Ujayi Pranayama.",
    yoga_hi: "सर्वांगासन, मत्स्यासन, उज्जायी प्राणायाम।",
    dos_en: "Eat balanced iodine, stay active, get regular tests.",
    dos_hi: "संतुलित आयोडीन खाएं, सक्रिय रहें, नियमित जांच कराएं।",
    donts_en: "Avoid soy products and raw cruciferous vegetables if severe.",
    donts_hi: "गंभीर होने पर सोया उत्पादों और कच्ची पत्तेदार सब्जियों से बचें।",
    consult_doctor_en: "Unexplained weight loss/gain or persistent fatigue.",
    consult_doctor_hi: "बिना किसी कारण के वजन कम होना/बढ़ना या लगातार थकान।",
  },
  {
    id: "asthma",
    name_en: "Asthma",
    name_hi: "अस्थमा",
    description_en: "Condition where airways narrow and swell.",
    description_hi: "वह स्थिति जिसमें वायुमार्ग संकुचित हो जाते हैं और सूज जाते हैं।",
    causes_en: "Allergens, air pollution, cold air.",
    causes_hi: "एलर्जी, वायु प्रदूषण, ठंडी हवा।",
    symptoms_en: "Wheezing, coughing, chest tightness.",
    symptoms_hi: "घबराहट, खांसी, सीने में जकड़न।",
    remedies_en: "Honey, Ginger, Mustard oil massage.",
    remedies_hi: "शहद, अदरक, सरसों के तेल की मालिश।",
    yoga_en: "Sukhasana, Bhujangasana, Kapalbhati.",
    yoga_hi: "सुखासन, भुजंगासन, कपालभाति।",
    dos_en: "Keep home dust-free, identify triggers, use inhaler as prescribed.",
    dos_hi: "घर को धूल मुक्त रखें, ट्रिगर्स की पहचान करें, बताए अनुसार इनहेलर का उपयोग करें।",
    donts_en: "Avoid smoking, dusty areas, and strong perfumes.",
    donts_hi: "धूम्रपान, धूल भरे क्षेत्रों और तेज इत्र से बचें।",
    consult_doctor_en: "Rapid worsening of shortness of breath or wheezing.",
    consult_doctor_hi: "सांस की तकलीफ या घरघराहट का तेजी से बिगड़ना।",
  },
    {
      id: "obesity",
      name_en: "Obesity",
      name_hi: "मोटापा",
      description_en: "Excessive body fat that increases health risk.",
      description_hi: "अत्यधिक शरीर की चर्बी जो स्वास्थ्य जोखिम को बढ़ाती है।",
      causes_en: "Unhealthy diet, lack of exercise, sleep deprivation.",
      causes_hi: "अस्वस्थ आहार, व्यायाम की कमी, नींद की कमी।",
      symptoms_en: "Breathlessness, increased sweating, snoring.",
      symptoms_hi: "सांस फूलना, पसीना बढ़ना, खर्राटे लेना।",
      remedies_en: "Lemon water with honey, Green tea, Apple cider vinegar.",
      remedies_hi: "शहद के साथ नींबू पानी, ग्रीन टी, एप्पल साइडर विनेगर।",
      yoga_en: "Surya Namaskar, Trikonasana, Plank.",
      yoga_hi: "सूर्य नमस्कार, त्रिकोणासन, प्लैंक।",
      dos_en: "Eat fiber-rich foods, drink water before meals, sleep 7-8 hours.",
      dos_hi: "फाइबर युक्त खाद्य पदार्थ खाएं, भोजन से पहले पानी पिएं, 7-8 घंटे सोएं।",
      donts_en: "Avoid junk food, late-night snacking, and sugary treats.",
      donts_hi: "जंक फूड, देर रात स्नैकिंग और मीठे व्यंजनों से बचें।",
      consult_doctor_en: "If BMI exceeds 30 or physical activity is painful.",
      consult_doctor_hi: "यदि बीएमआई 30 से अधिक हो या शारीरिक गतिविधि दर्दनाक हो।",
    },
    {
      id: "heart-disease",
      name_en: "Heart Disease",
      name_hi: "हृदय रोग",
      description_en: "Range of conditions that affect your heart.",
      description_hi: "ऐसी स्थितियों की श्रेणी जो आपके हृदय को प्रभावित करती हैं।",
      causes_en: "High BP, high cholesterol, smoking.",
      causes_hi: "उच्च बीपी, उच्च कोलेस्ट्रॉल, धूम्रपान।",
      symptoms_en: "Chest pain, shortness of breath, pain in neck/jaw.",
      symptoms_hi: "सीने में दर्द, सांस की तकलीफ, गर्दन/जबड़े में दर्द।",
      remedies_en: "Garlic, Omega-3 fatty acids, Turmeric milk.",
      remedies_hi: "लहसुन, ओमेगा -3 फैटी एसिड, हल्दी वाला दूध।",
      yoga_en: "Tadasana, Vrikshasana, Gomukhasana.",
      yoga_hi: "ताड़ासन, वृक्षासन, गोमुखासन।",
      dos_en: "Eat heart-healthy fats, manage stress, regular checkups.",
      dos_hi: "हृदय के लिए स्वस्थ वसा खाएं, तनाव प्रबंधन करें, नियमित जांच कराएं।",
      donts_en: "Avoid trans fats, excessive salt, and smoking.",
      donts_hi: "ट्रांस फैट, अत्यधिक नमक और धूम्रपान से बचें।",
      consult_doctor_en: "If you experience chest pressure or fainting.",
      consult_doctor_hi: "यदि आपको सीने में दबाव या बेहोशी महसूस हो।",
    },
    {
      id: "gastric-problems",
      name_en: "Gastric Problems",
      name_hi: "गैस्ट्रिक समस्याएं",
      description_en: "Issues related to stomach gas, acidity, and bloating.",
      description_hi: "पेट की गैस, एसिडिटी और सूजन से संबंधित समस्याएं।",
      causes_en: "Overeating, spicy food, eating too fast.",
      causes_hi: "अधिक खाना, तीखा खाना, बहुत जल्दी खाना।",
      symptoms_en: "Bloating, stomach pain, burping, heartburn.",
      symptoms_hi: "सूजन, पेट दर्द, डकार, सीने में जलन।",
      remedies_en: "Ajwain with warm water, Ginger, Fennel seeds.",
      remedies_hi: "गुनगुने पानी के साथ अजवाइन, अदरक, सौंफ।",
      yoga_en: "Pawanmuktasana, Vajrasana, Balasana.",
      yoga_hi: "पवनमुक्तासन, वज्रासन, बालासन।",
      dos_en: "Eat smaller meals, chew food properly, drink plenty of water.",
      dos_hi: "छोटा भोजन करें, भोजन को ठीक से चबाएं, खूब पानी पिएं।",
      donts_en: "Avoid carbonated drinks, oily food, and skipping meals.",
      donts_hi: "कार्बोनेटेड ड्रिंक्स, तैलीय भोजन और भोजन छोड़ने से बचें।",
      consult_doctor_en: "If pain is severe or accompanied by weight loss.",
      consult_doctor_hi: "यदि दर्द गंभीर हो या वजन कम होने के साथ हो।",
    },

];
