export const diseasesData = [
  {
    id: "diabetes",
    nameEn: "Diabetes",
    nameHi: "मधुमेह (Diabetes)",
    descEn: "A chronic condition that affects how your body processes blood sugar (glucose).",
    descHi: "एक पुरानी स्थिति जो आपके शरीर के रक्त शर्करा (ग्लूकोज) को संसाधित करने के तरीके को प्रभावित करती है।",
    causesEn: ["Genetics", "Obesity", "Lack of physical activity"],
    causesHi: ["आनुवंशिकी", "मोटापा", "शारीरिक गतिविधि की कमी"],
    symptomsEn: ["Increased thirst", "Frequent urination", "Fatigue"],
    symptomsHi: ["प्यास बढ़ना", "बार-बार पेशाब आना", "थकान"],
    remediesEn: ["Cinnamon water", "Bitter gourd juice", "Fenugreek seeds"],
    remediesHi: ["दालचीनी का पानी", "करेले का रस", "मेथी के दाने"],
    yogaEn: ["Paschimottanasana", "Ardha Matsyendrasana"],
    yogaHi: ["पश्चिमोत्तानासन", "अर्ध मत्स्येंद्रासन"],
    dosEn: ["Eat fiber-rich foods", "Exercise daily"],
    dosHi: ["फाइबर युक्त भोजन करें", "प्रतिदिन व्यायाम करें"],
    dontsEn: ["Avoid sugary drinks", "Limit processed carbs"],
    dontsHi: ["मीठे पेय पदार्थों से बचें", "प्रसंस्कृत कार्ब्स को सीमित करें"],
    consultEn: "If blood sugar is consistently over 200 mg/dL.",
    consultHi: "यदि रक्त शर्करा लगातार 200 mg/dL से ऊपर है।"
  },
  {
    id: "blood-pressure",
    nameEn: "Blood Pressure (Hypertension)",
    nameHi: "रक्तचाप (High BP)",
    descEn: "A condition in which the force of the blood against the artery walls is too high.",
    descHi: "ऐसी स्थिति जिसमें धमनी की दीवारों के खिलाफ रक्त का बल बहुत अधिक होता है।",
    causesEn: ["High salt intake", "Stress", "Age"],
    causesHi: ["नमक का अधिक सेवन", "तनाव", "उम्र"],
    symptomsEn: ["Headaches", "Shortness of breath", "Nosebleeds"],
    symptomsHi: ["सिरदर्द", "सांस लेने में तकलीफ", "नाक से खून आना"],
    remediesEn: ["Garlic", "Lemon water", "Hibiscus tea"],
    remediesHi: ["लहसुन", "नींबू पानी", "गुड़हल की चाय"],
    yogaEn: ["Shavasana", "Tadasana"],
    yogaHi: ["शवासन", "ताड़ासन"],
    dosEn: ["Reduce sodium intake", "Manage stress"],
    dosHi: ["सोडियम का सेवन कम करें", "तनाव प्रबंधित करें"],
    dontsEn: ["Avoid smoking", "Limit caffeine"],
    dontsHi: ["धूम्रपान से बचें", "कैफीन सीमित करें"],
    consultEn: "If BP is consistently above 140/90 mmHg.",
    consultHi: "यदि बीपी लगातार 140/90 mmHg से ऊपर है।"
  },
  {
    id: "thyroid",
    nameEn: "Thyroid",
    nameHi: "थायराइड",
    descEn: "A condition where the thyroid gland doesn't produce the right amount of hormones.",
    descHi: "ऐसी स्थिति जहां थायराइड ग्रंथि सही मात्रा में हार्मोन का उत्पादन नहीं करती है।",
    causesEn: ["Iodine deficiency", "Autoimmune diseases", "Inflammation"],
    causesHi: ["आयोडीन की कमी", "ऑटोइम्यून रोग", "सूजन"],
    symptomsEn: ["Weight changes", "Mood swings", "Hair loss"],
    symptomsHi: ["वजन में बदलाव", "मूड में बदलाव", "बालों का झड़ना"],
    remediesEn: ["Ginger tea", "Coconut oil", "Walnuts"],
    remediesHi: ["अदरक की चाय", "नारियल तेल", "अखरोट"],
    yogaEn: ["Sarvangasana", "Halasana"],
    yogaHi: ["सर्वांगासन", "हलासन"],
    dosEn: ["Eat iodine-rich foods", "Get enough sleep"],
    dosHi: ["आयोडीन युक्त भोजन करें", "पर्याप्त नींद लें"],
    dontsEn: ["Avoid soy products", "Limit processed foods"],
    dontsHi: ["सोया उत्पादों से बचें", "प्रसंस्कृत खाद्य पदार्थों को सीमित करें"],
    consultEn: "If you feel extreme fatigue or unexplained weight loss/gain.",
    consultHi: "यदि आप अत्यधिक थकान या बिना कारण वजन घटने/बढ़ने का अनुभव करते हैं।"
  },
  {
    id: "asthma",
    nameEn: "Asthma",
    nameHi: "अस्थमा (दमा)",
    descEn: "A condition in which your airways narrow and swell and may produce extra mucus.",
    descHi: "ऐसी स्थिति जिसमें आपके वायुमार्ग संकीर्ण और सूज जाते हैं और अतिरिक्त बलगम पैदा कर सकते हैं।",
    causesEn: ["Airborne allergens", "Respiratory infections", "Physical activity"],
    causesHi: ["हवा में मौजूद एलर्जी", "श्वसन संक्रमण", "शारीरिक गतिविधि"],
    symptomsEn: ["Shortness of breath", "Chest tightness", "Wheezing"],
    symptomsHi: ["सांस की तकलीफ", "सीने में जकड़न", "घबराहट"],
    remediesEn: ["Honey", "Ginger", "Eucalyptus oil"],
    remediesHi: ["शहद", "अदरक", "नीलगिरी का तेल"],
    yogaEn: ["Bhujangasana", "Pranayama"],
    yogaHi: ["भुजंगासन", "प्राणायाम"],
    dosEn: ["Identify triggers", "Keep inhaler ready"],
    dosHi: ["ट्रिगर्स की पहचान करें", "इनहेलर तैयार रखें"],
    dontsEn: ["Avoid smoking", "Stay away from dust"],
    dontsHi: ["धूम्रपान से बचें", "धूल से दूर रहें"],
    consultEn: "If wheezing or breathlessness worsens rapidly.",
    consultHi: "यदि घबराहट या सांस फूलना तेजी से बिगड़ता है।"
  },
  {
    id: "heart-disease",
    nameEn: "Heart Disease",
    nameHi: "हृदय रोग",
    descEn: "A range of conditions that affect your heart, including blood vessel diseases.",
    descHi: "ऐसी स्थितियां जो आपके दिल को प्रभावित करती हैं, जिसमें रक्त वाहिका रोग शामिल हैं।",
    causesEn: ["Smoking", "High cholesterol", "Obesity"],
    causesHi: ["धूम्रपान", "उच्च कोलेस्ट्रॉल", "मोटापा"],
    symptomsEn: ["Chest pain", "Shortness of breath", "Numbness in limbs"],
    symptomsHi: ["सीने में दर्द", "सांस की तकलीफ", "अंगों में सुन्नता"],
    remediesEn: ["Arjun bark tea", "Garlic", "Green tea"],
    remediesHi: ["अर्जुन की छाल की चाय", "लहसुन", "ग्रीन टी"],
    yogaEn: ["Trikonasana", "Sukhasana"],
    yogaHi: ["त्रिकोणासन", "सुखासन"],
    dosEn: ["Eat heart-healthy fats", "Monitor BP"],
    dosHi: ["हृदय के अनुकूल वसा खाएं", "बीपी की निगरानी करें"],
    dontsEn: ["Avoid trans fats", "Limit red meat"],
    dontsHi: ["ट्रांस फैट से बचें", "रेड मीट सीमित करें"],
    consultEn: "If you experience sudden chest pain or dizziness.",
    consultHi: "यदि आप अचानक सीने में दर्द या चक्कर आने का अनुभव करते हैं।"
  },
  {
    id: "obesity",
    nameEn: "Obesity",
    nameHi: "मोटापा",
    descEn: "A complex disease involving an excessive amount of body fat.",
    descHi: "शरीर में अत्यधिक वसा वाली एक जटिल बीमारी।",
    causesEn: ["Unhealthy diet", "Inactivity", "Sleep deprivation"],
    causesHi: ["अस्वस्थ आहार", "निष्क्रियता", "नींद की कमी"],
    symptomsEn: ["High BMI", "Back and joint pain", "Snoring"],
    symptomsHi: ["उच्च बीएमआई", "पीठ और जोड़ों का दर्द", "खर्राटे लेना"],
    remediesEn: ["Warm lemon water", "Green tea", "Apple cider vinegar"],
    remediesHi: ["गर्म नींबू पानी", "ग्रीन टी", "सेब का सिरका"],
    yogaEn: ["Surya Namaskar", "Navasana"],
    yogaHi: ["सूर्य नमस्कार", "नौकासन"],
    dosEn: ["Eat small, frequent meals", "Walk daily"],
    dosHi: ["थोड़ा-थोड़ा और बार-बार भोजन करें", "प्रतिदिन टहलें"],
    dontsEn: ["Avoid junk food", "Stop late-night snacking"],
    dontsHi: ["जंक फूड से बचें", "देर रात नाश्ता करना बंद करें"],
    consultEn: "If obesity starts affecting your mobility or mental health.",
    consultHi: "यदि मोटापा आपकी गतिशीलता या मानसिक स्वास्थ्य को प्रभावित करने लगे।"
  },
  {
    id: "gastric-problems",
    nameEn: "Gastric Problems",
    nameHi: "गैस्ट्रिक समस्याएं (Gas/Acidity)",
    descEn: "Issues related to the digestive system, including bloating and acidity.",
    descHi: "पाचन तंत्र से संबंधित समस्याएं, जिनमें सूजन और एसिडिटी शामिल है।",
    causesEn: ["Spicy food", "Overeating", "Eating too fast"],
    causesHi: ["मसालेदार भोजन", "अधिक खाना", "बहुत जल्दी खाना"],
    symptomsEn: ["Bloating", "Stomach pain", "Heartburn"],
    symptomsHi: ["पेट फूलना", "पेट दर्द", "सीने में जलन"],
    remediesEn: ["Buttermilk", "Ginger water", "Fennel seeds (Saunf)"],
    remediesHi: ["छाछ", "अदरक का पानी", "सौंफ"],
    yogaEn: ["Pawanmuktasana", "Vajrasana"],
    yogaHi: ["पवनमुक्तासन", "वज्रासन"],
    dosEn: ["Drink plenty of water", "Eat at fixed times"],
    dosHi: ["खूब पानी पिएं", "निश्चित समय पर भोजन करें"],
    dontsEn: ["Avoid carbonated drinks", "Don't sleep immediately after eating"],
    dontsHi: ["कार्बोनेटेड पेय पदार्थों से बचें", "खाने के तुरंत बाद न सोएं"],
    consultEn: "If severe stomach pain or persistent vomiting occurs.",
    consultHi: "यदि पेट में तेज दर्द या लगातार उल्टी हो रही हो।"
  }
];
